"""Ma-Doh backend schema"""

import sqlalchemy as sa
from alembic import op

revision = "4c5d7769701c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.CheckConstraint("currency = 'KES'", name="account_kes"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "captures",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "account_id", "source", "fingerprint", name="uq_capture_input"
        ),
    )
    op.create_index(op.f("ix_captures_user_id"), "captures", ["user_id"], unique=False)
    op.create_table(
        "transaction_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("capture_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("destination_account_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("counterparty", sa.String(length=160), nullable=True),
        sa.Column("external_reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_drafts_capture_id"), "transaction_drafts", ["capture_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_drafts_user_id"), "transaction_drafts", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("destination_account_id", sa.String(length=36), nullable=True),
        sa.Column("draft_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("counterparty", sa.String(length=160), nullable=True),
        sa.Column("external_reference", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(type = 'transfer' AND destination_account_id IS NOT NULL AND destination_account_id <> account_id AND category IS NULL) OR (type <> 'transfer' AND destination_account_id IS NULL AND category IS NOT NULL)",
            name="transfer_shape",
        ),
        sa.CheckConstraint("currency = 'KES'", name="transaction_kes"),
        sa.CheckConstraint("type IN ('income', 'expense', 'transfer')", name="transaction_type"),
        sa.CheckConstraint("amount > 0", name="positive_amount"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["transaction_drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id"),
        sa.UniqueConstraint(
            "user_id", "account_id", "external_reference", name="uq_transaction_reference"
        ),
    )
    op.create_index(
        "ix_transaction_owner_date", "transactions", ["user_id", "occurred_on"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        # The backend connects as the table owner and scopes every query itself.
        # No browser/Data API access to financial tables is permitted by default.
        for table in ("users", "accounts", "captures", "transaction_drafts", "transactions"):
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transaction_owner_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_transaction_drafts_user_id"), table_name="transaction_drafts")
    op.drop_index(op.f("ix_transaction_drafts_capture_id"), table_name="transaction_drafts")
    op.drop_table("transaction_drafts")
    op.drop_index(op.f("ix_captures_user_id"), table_name="captures")
    op.drop_table("captures")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    # ### end Alembic commands ###
